algoritmo "areaQuadrado"
// Função : Calcular a area do quadrado
// Autor : Paola Onorio Zaratini
// Data : 28/02/2024
// Seção de Declarações 
var

//lado variavel de entrada
//area variavel de processamento e saida
lado,area : real

inicio
//entrada
escreval("Digite o lado do quadrado: ")
leia (lado)


//processamento
area <- lado* lado

//Saida
escreval("A Area do quadrado e:",area)

fimalgoritmo
